GET http://localhost:8080/api/auth/getuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imhha2kiLCJ1c2VybmFtZSI6Imhha2kiLCJlbWFpbCI6Imhha2l4ZXJAZ21haWwuY29tIiwiaWF0IjoxNzYzMDY0MjM2LCJleHAiOjE3NjM2NjkwMzZ9.0wXIxcJCgaIp_73rzDoBQCYfYvATcV_bdguZ5eYasp8