GET http://localhost:8080/api/auth/getuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imhha2kiLCJ1c2VybmFtZSI6Imhha2kiLCJlbWFpbCI6Imhha2l4ZXJAZ21haWwuY29tIiwiZm9sbG93ZXJzIjowLCJmb2xsb3dpbmciOjAsImNvdXJzZXMiOltdLCJhdmF0YXIiOiJodHRwczovL2Nkbi5rb3JkLmxpdmUvc2VydmUvMFVoZUdkajFUSmNDLmpwZyIsImxldmVsIjoiYnJvbnplIiwiam9pbmVkX2F0IjoiMjAyNS0xMS0wNFQxOToxOToxNS44MDhaIiwiaWF0IjoxNzYyMjkyMDc3LCJleHAiOjE3NjI4OTY4Nzd9.W5YZo-GY206nJhhznqbryN3TqZ-y8FkouQnB1mwzCD0